version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    restart: on-failure
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/fliq
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    restart: on-failure
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
